// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Rvostgm-qrhL5E-FA3LLx6jTEsVMEEs',
    appId: '1:310815038944:web:b89cca46cf2f04872a9f85',
    messagingSenderId: '310815038944',
    projectId: 'e-commerce-flutter-app-aeae5',
    authDomain: 'e-commerce-flutter-app-aeae5.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-app-aeae5.appspot.com',
    measurementId: 'G-QNFJPHG0ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqrSOdlZEYQtThZyjeLvt7NziUv3nGXg',
    appId: '1:310815038944:android:8c4e3f995ee5ceea2a9f85',
    messagingSenderId: '310815038944',
    projectId: 'e-commerce-flutter-app-aeae5',
    storageBucket: 'e-commerce-flutter-app-aeae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukfwmUZB-CdKEBsLBiDR3vp1Cw82Jmj4',
    appId: '1:310815038944:ios:26b23b2da72d74b82a9f85',
    messagingSenderId: '310815038944',
    projectId: 'e-commerce-flutter-app-aeae5',
    storageBucket: 'e-commerce-flutter-app-aeae5.appspot.com',
    iosBundleId: 'com.example.flutterCounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAukfwmUZB-CdKEBsLBiDR3vp1Cw82Jmj4',
    appId: '1:310815038944:ios:9a663d76a78a9d262a9f85',
    messagingSenderId: '310815038944',
    projectId: 'e-commerce-flutter-app-aeae5',
    storageBucket: 'e-commerce-flutter-app-aeae5.appspot.com',
    iosBundleId: 'com.example.flutterCounterApp.RunnerTests',
  );
}
